### ISSUE TITLE
[3.x] TODO

### ISSUE THREAD

**Issue by kbond** [liip/LiipMonitorBundle#288]
Looking for feedback on the next iteration of this bundle.

See [README](https://github.com/kbond/LiipMonitorBundle/blob/next-3.x/README.md) for docs, specifically the [upgrade notes](https://github.com/kbond/LiipMonitorBundle/blob/next-3.x/README.md#upgrading-from-2x-to-3x).

TODO
- [x] remove need for `Check::label()` (use class short name by default)
- [ ] add remaining missing checks from 2.x
- [x] re-add email notification
- [ ] Event docs
- [x] Logging event subscriber
- [x] ~_Nagios_ support? I have no idea what this is - does anyone need it? If so, what's required?~
- [x] https://github.com/liip/LiipMonitorBundle/pull/287

**Comment by Chris53897** [comment]
>> Nagios support?
I did not take a deeper look. 
But my collegue did say, that Nagios ist not longer state of the art. https://checkmk.com/guides/nagios-alternative
For our company we plan to integtare CheckMK.

Best choice could possibly https://prometheus.io/
But i need to have a deeper look how this could be done.


>> I would suggest to bump dependencies

**Comment by kbond** [comment]
Thanks, I'm going to remove Nagios from the todo. As I use OhDear, I think I'll add an abstract controller for this to use as a template for other integrations.

**Comment by Chris53897** [comment]
+1 for OhDear. As we use it as well.
